FAForever/downlords-faf-client

- src/main/java/com/faforever/client/chat/ChatService.java
- src/main/java/com/faforever/client/chat/MockChatService.java
- src/main/java/com/faforever/client/chat/PircBotXChatService.java
- src/main/java/com/faforever/client/legacy/LobbyServerAccessorImpl.java
- src/main/java/com/faforever/client/legacy/domain/Notice.java
- src/main/java/com/faforever/client/legacy/domain/NoticeInfo.java
- src/main/java/com/faforever/client/legacy/domain/ServerObjectType.java
- src/main/java/com/faforever/client/login/LoginController.java
- src/main/java/com/faforever/client/login/LoginFailedException.java
- src/main/java/com/faforever/client/main/MainController.java
- src/main/java/com/faforever/client/user/UserService.java
- src/main/java/com/faforever/client/user/UserServiceImpl.java
- src/main/java/com/faforever/client/util/UID.java
- src/main/resources/themes/default/login.fxml
- src/main/resources/themes/default/main.fxml
Hello,
as you asked on your stream, here's some contribution. 
I don't know if it's any good, I have never really done anything in JavaFX. :-)
That PircBotX might need some attention, it likes to throw exceptions when logging out immediately after login.
> Login & Logout

- build.gradle
- src/main/java/com/faforever/client/legacy/MockLobbyServerAccessor.java
- src/main/java/com/faforever/client/main/MainController.java
* Closes #164
* Fixed MockLobbyServerAccessor
> Taskbar Progress

- src/main/java/com/faforever/client/chat/AbstractChatTabController.java
> Generate avatar in notification from player ID

- src/main/java/com/faforever/client/fa/LaunchCommandBuilder.java
- src/test/java/com/faforever/client/main/UserMenuControllerTest.java
No longer necessary since it has been fixed in game lobby
Fixes #251
> Don't create user profile

- src/main/java/com/faforever/client/game/GameType.java
- src/main/java/com/faforever/client/game/GamesController.java
> Don't show non-custom games

- src/main/java/com/faforever/client/preferences/PreferencesService.java
> Steam version not working

- src/main/java/com/faforever/client/chat/ChannelTabController.java
- src/main/java/com/faforever/client/chat/FilterUserController.java
> #183 apply chat filter to new users

- .idea/modules/downlords-faf-client.iml
- src/main/java/com/faforever/client/chat/AbstractChatTabController.java
- src/main/java/com/faforever/client/chat/ChannelTabController.java
- src/main/java/com/faforever/client/chat/PircBotXChatService.java
- src/main/java/com/faforever/client/config/UiConfig.java
- src/main/java/com/faforever/client/fa/OnGameFullFaWindowFlasher.java
- src/main/java/com/faforever/client/fa/OnGameFullNotifier.java
- src/main/java/com/faforever/client/fx/PlatformService.java
- src/main/java/com/faforever/client/fx/PlatformServiceImpl.java
- src/main/java/com/faforever/client/game/GameInfoBean.java
- src/main/java/com/faforever/client/game/GameService.java
- src/main/java/com/faforever/client/game/GameServiceImpl.java
- src/main/java/com/faforever/client/game/GameTooltipController.java
- src/main/java/com/faforever/client/game/GamesController.java
- src/main/java/com/faforever/client/main/MainController.java
- src/main/java/com/faforever/client/notification/TransientNotification.java
- src/main/java/com/faforever/client/notification/TransientNotificationController.java
- src/main/java/com/faforever/client/player/PlayerServiceImpl.java
- src/main/java/com/faforever/client/preferences/PreferencesService.java
- src/main/java/com/faforever/client/relay/GpgClientCommand.java
- src/main/java/com/faforever/client/relay/LocalRelayServerImpl.java
- src/main/java/com/faforever/client/relay/event/GameFullEvent.java
- src/main/java/com/faforever/client/replay/LocalReplayInfo.java
- src/main/resources/application.properties
- src/main/resources/i18n/Messages.properties
- src/test/java/com/faforever/client/fa/OnGameFullNotifierTest.java
- src/test/java/com/faforever/client/game/GameInfoMessageBuilder.java
- src/test/java/com/faforever/client/game/GameServiceImplTest.java
- src/test/java/com/faforever/client/relay/LocalRelayServerImplTest.java
Show a transient notification when the the game sends a GameFull-Command as requested in #141 .
Following tasks remain open:
- show a preview of the game (i.e. preview of current map)
- click on notification opens ingame lobby
I added TODOs for these.
_Please note the the current GameFull-Implementation of the game is buggy. It does not fire when the last slot is closed. It fires multiple times if the last slot is filled with an AI. Behavior was not tested with human players._
Connect to #141
> Notify player when game is full (#141)

- src/main/java/com/faforever/client/game/CreateGameController.java
- src/main/java/com/faforever/client/remote/FafServerAccessorImpl.java
- src/main/resources/i18n/messages.properties
- src/test/java/com/faforever/client/game/CreateGameControllerTest.java
It introduces wonderful and working unit tests
It is even more wonderful than it normally is :D
fixes #480
closes #480
P.S. Not blaming Travis personally, but if he is not gonna approve of this. I am gonna ****
I know I could have used the Argumen Capturer or whatever his name is but I wanted to als test the binding ;)
> That is supposed to be a perfect PR

- src/main/java/com/faforever/client/game/GamesTableController.java
- src/main/java/com/faforever/client/preferences/Preferences.java
- src/test/java/com/faforever/client/game/GamesTableControllerTest.java
Fixes #541. 
Works for me, tests are green. Solved it?
> Store sorted columns in preferences and restore them in initialization.

- src/main/java/com/faforever/client/map/MapDetailController.java
- src/main/resources/theme/vault/map/map_detail.fxml
- src/test/java/com/faforever/client/map/MapDetailControllerTest.java
> Fixes unclickable install/uninstall button

- src/main/java/com/faforever/client/news/LegacyNewsService.java
- src/main/java/com/faforever/client/news/NewsCategory.java
- src/main/java/com/faforever/client/news/NewsItem.java
- src/main/java/com/faforever/client/news/NewsListItemController.java
- src/main/java/com/faforever/client/theme/UiService.java
Introduces an Enum for NewsCategories
> Fixes #507 images for news categories

- src/main/java/com/faforever/client/config/ClientProperties.java
- src/main/java/com/faforever/client/login/LoginController.java
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/main/resources/theme/login.fxml
- src/test/java/com/faforever/client/login/LoginControllerTest.java
> redirects users to the website to register or reset password

- src/main/java/com/faforever/client/main/MainController.java
- src/test/java/com/faforever/client/main/MainControllerTest.java
> Fixes #468 toast position

- src/main/java/com/faforever/client/game/GameDetailController.java
Main thing I did was to give game, that is set the Controller the name newGame, so you do not get confused with game and this.game. Further I removed the Weakreference of the Invalidationlistener. Weakreferences are meant to be used if the listeners might not the removed correctly to avoid memory leakages. So this is not needed in this context and makes removing the listener more difficult. On Top a have a second check if the correct game is updated.
Fixes #573
> Refactored code

- src/main/java/com/faforever/client/news/NewsListItemController.java
> Fills Image view when news category is set and not before

- src/main/java/com/faforever/client/chat/AbstractChatTabController.java
- src/main/java/com/faforever/client/chat/ChannelTabController.java
- src/main/java/com/faforever/client/chat/PrivateChatTabController.java
- src/main/java/com/faforever/client/game/GameServiceImpl.java
- src/main/java/com/faforever/client/replay/ExternalReplayInfoGenerator.java
- src/main/java/com/faforever/client/replay/ReplayServiceImpl.java
- src/main/resources/i18n/messages.properties
- src/main/resources/i18n/messages_de_DE.properties
- src/test/java/com/faforever/client/chat/AbstractChatTabControllerTest.java
- src/test/java/com/faforever/client/chat/ChannelTabControllerTest.java
- src/test/java/com/faforever/client/chat/PrivateChatTabControllerTest.java
- src/test/java/com/faforever/client/game/GameServiceImplTest.java
> Shows ReplayDetail onGame Finished

- src/main/java/com/faforever/client/api/FafApiAccessorImpl.java
- src/main/java/com/faforever/client/api/dto/Clan.java
- src/main/java/com/faforever/client/api/dto/ClanMembership.java
- src/main/java/com/faforever/client/api/dto/Player.java
- src/main/java/com/faforever/client/chat/ChatUserItemController.java
- src/main/java/com/faforever/client/clan/Clan.java
- src/main/java/com/faforever/client/clan/ClanTooltipController.java
- src/main/resources/theme/chat/clan_tooltip.fxml
- src/test/java/com/faforever/client/chat/AbstractChatTabControllerTest.java
> Gets Clan features running again

- src/main/java/com/faforever/client/mod/ModUploadController.java
> Runs UI code on Ui thread

- src/main/java/com/faforever/client/api/FafApiAccessor.java
- src/main/java/com/faforever/client/api/FafApiAccessorImpl.java
- src/main/java/com/faforever/client/api/MockFafApiAccessor.java
- src/main/java/com/faforever/client/game/CreateGameController.java
- src/main/java/com/faforever/client/map/MapDetailController.java
- src/main/java/com/faforever/client/mod/Mod.java
- src/main/java/com/faforever/client/mod/ModCardController.java
- src/main/java/com/faforever/client/mod/ModDetailController.java
- src/main/java/com/faforever/client/mod/ModService.java
- src/main/java/com/faforever/client/mod/ModServiceImpl.java
- src/main/java/com/faforever/client/mod/UninstallModTask.java
- src/main/java/com/faforever/client/remote/FafService.java
- src/main/java/com/faforever/client/remote/FafServiceImpl.java
- src/main/java/com/faforever/client/vault/review/Review.java
- src/main/java/com/faforever/client/vault/review/ReviewService.java
- src/main/resources/i18n/messages.properties
- src/main/resources/theme/style.css
- src/main/resources/theme/vault/mod/mod_detail.fxml
- src/test/java/com/faforever/client/map/MapServiceImplTest.java
- src/test/java/com/faforever/client/mod/ModDetailControllerTest.java
- src/test/java/com/faforever/client/mod/ModInfoBeanBuilder.java
- src/test/java/com/faforever/client/mod/ModServiceImplTest.java
- src/test/java/com/faforever/client/remote/FafServiceImplTest.java
- src/test/java/com/faforever/client/vault/review/ReviewServiceTest.java
> Fix #406 display mod version (& size)

- .idea/modules/downlords-faf-client.iml
- src/main/java/com/faforever/client/fa/ForgedAllianceService.java
- src/main/java/com/faforever/client/fa/ForgedAllianceServiceImpl.java
- src/main/java/com/faforever/client/fa/OnGameFullNotifier.java
- src/main/java/com/faforever/client/game/GameAddedEvent.java
- src/main/java/com/faforever/client/game/GameRemovedEvent.java
- src/main/java/com/faforever/client/game/GameServiceImpl.java
- src/main/java/com/faforever/client/game/GameUpdatedEvent.java
- src/main/java/com/faforever/client/main/MainController.java
- src/main/java/com/faforever/client/net/SocketUtil.java
- src/main/java/com/faforever/client/player/PlayerServiceImpl.java
- src/main/java/com/faforever/client/relay/LocalRelayServerImpl.java
- src/main/java/com/faforever/client/relay/event/GameFullEvent.java
- src/test/java/com/faforever/client/fa/OnGameFullNotifierTest.java
- src/test/java/com/faforever/client/game/GameServiceImplTest.java
- src/test/java/com/faforever/client/player/PlayerServiceImplTest.java
> Game Full Notification

- src/main/java/com/faforever/client/game/Game.java
- src/main/java/com/faforever/client/game/GameServiceImpl.java
- src/main/resources/application.yml
- src/test/java/com/faforever/client/fa/OnGameFullNotifierTest.java
- src/test/java/com/faforever/client/game/GameServiceImplTest.java
> Run all game updates on application thread

- build.gradle
Changes Version in build.gradle
> get tests running

- src/main/resources/fa/init_template.lua
> Advanced icon pack

- src/main/java/com/faforever/client/chat/PircBotXChatService.java
> Properly register new users to IRC

- src/main/java/com/faforever/client/remote/domain/GameStatus.java
> Converts to lower case

- src/main/java/com/faforever/client/rankedmatch/Ladder1v1Controller.java
> Hides Rating hint if the player is learned

- src/main/java/com/faforever/client/replay/ReplayServiceImpl.java
> Fixes #671

- src/main/java/com/faforever/client/achievements/AchievementServiceImpl.java
- src/test/java/com/faforever/client/achievements/AchievementServiceImplTest.java
> Resolves async Issue with achievements loading

- src/main/resources/theme/vault/map/map_detail.fxml
Changes layout xml of map detail
Fixes #688
> Avoid overlapping controls

- src/main/java/com/faforever/client/main/MainController.java
> changed anchor to top right

- src/main/resources/theme/play/games_table.fxml
Makes width of column bigger...
Fixes #683
> Fix password lock symbol

- src/main/java/com/faforever/client/map/MapUploadController.java
Changed width and height to use kilometres instead of pixels.
Fixes #666
> Fix wrong size of map on upload

- src/main/java/com/faforever/client/game/GameTooltipController.java
Unregisters listener from GameTooltip.class when next game is set.
Fixes #695
> Unregister listener from GameTooltip.class

- src/main/java/com/faforever/client/config/AsyncConfig.java
Calls shutdownNow().
Fixes #696
> Close ExectorSevice on app closure

- src/main/java/com/faforever/client/theme/UiServiceImpl.java
Deletes cache directory on close and start up
Fixes #684
> Delete cache directory on close

- src/main/java/com/faforever/client/chat/ChatUserContextMenuController.java
- src/main/resources/theme/chat/chat_user_context_menu.fxml
- src/test/java/com/faforever/client/chat/ChatUserContextMenuControllerTest.java
> Check if a user has an id before showing user info

- src/main/java/com/faforever/client/game/CustomGamesController.java
- src/main/java/com/faforever/client/game/GamesTableController.java
- src/main/java/com/faforever/client/preferences/Preferences.java
- src/main/resources/i18n/messages.properties
- src/main/resources/i18n/messages_de_DE.properties
- src/main/resources/theme/play/custom_games.fxml
- src/test/java/com/faforever/client/game/CustomGamesControllerTest.java
Added a checkbox to give user the option to hide modded games
Fixes #641
> Add option to hide games with mods
